---
title: "Untitled"
output: pdf_document
---


```{r}
library(vegan)
library(magrittr)
library(tidyverse)
set.seed(1)
```


```{r}
df <- read.csv('HIVRC/processed_hiv_bcfs.csv', row.names=1)
md <- read.csv('HIVRC/processed_hiv_metadata.csv', row.names=1)

md %<>% filter(region!='')
df <- df[ row.names(md), ]

```

```{r}
ad_out <- adonis2(df ~ ExtractionKit_grouped3 + region + Swab.type, 
                  data = md, 
                  method='euclidean',
                  permutations=99999
                  )

```

```{r}
ad_out %>% as.data.frame() %>% write.csv('../results/HIVRC/adonis-output.csv')
```

```{r}
qq <- df==0

ad_out <- adonis2(qq ~  region + ExtractionKit_grouped3 + Swab.type, 
                  data = md, 
                  method='euclidean',
                  permutations=99999
                  )

ad_out
```



```{r}
tmp <- (1*qq) %>% as.matrix()
row.names(tmp) <- paste(row.names(tmp), 
                        md[row.names(tmp),]$region
                        )

colnames(tmp) <- rep('', ncol(tmp))

YlOrBr <- c("blue", "#FE9929")
coul <- colorRampPalette(YlOrBr)(2)
library(gplots)

distfunction <- function(x) dist(x, method='manhattan', p=1)


pdf(file="../results/HIVRC/16s-region-species-presence.pdf", 
    width=10)
tmp %>% heatmap(scale='none',
                distfun=distfunction,
                col=coul
                )
dev.off()
```





