---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
getwd()
```


```{r}
list.files()

list.files('../../data/Metabolites/')
```


```{r}
read.csv('../../data/Metabolites/new/otu.csv', row.names=1)
```


```{r}
read.csv('../../data/Metabolites/combat-out.csv', row.names=1)
```



```{r}
library(melonnpan)
df <- read.csv('../../results/Metabolites/df_inputs.csv', row.names=1)
md <- read.csv('../../results/Metabolites/df_metadata.csv', row.names=1)
```


```{r}




metag_train <- df[df$X0==1, 2:ncol(df)]
metag_train <- metag_train[, (metag_train > 0 ) %>% colSums() > 150]
metag_val <- df[df$X0!=1, colnames(metag_train)]

metag_train <- metag_train[, (metag_val > 0 ) %>% colSums() > 25]
metag_val <- metag_val[, (metag_val > 0 ) %>% colSums() > 25]

metab <- md[, 4:748] / md[, 4:748] %>% rowSums
metab <- metab[, ( metab != 0 ) %>% colSums() > 200]

metab <- metab[, ( metab %>% apply(MARGIN=2, FUN = function(x) length(unique(x))) > 5 )]


melonnpan.train(metab = metab[row.names(metag_train),], 
                metag =   metag_train / metag_train %>% rowSums , 
                output='melonnpan_out/', 
                cutoff=1e3#.5
                )

?melonnpan.train

list.files('melonnpan_out/')



melonnpan.predict( metag_val / metag_val %>% rowSums, 
                   weight.matrix = 'melonnpan_out/MelonnPan_Trained_Weights.txt',
                   train.metag = metag_train / metag_train %>% rowSums,
                   output='melonnpan_out/')


metab %>% write_csv('melonnpan_out/true_metabs.csv')

# ?melonnpan.predict


metab %>% dim

# colnames(md)[749:ncol(md)]
```


```{r}
dir.create('melonnpan_out2')

metag_train <- df[df$X0!=1, 2:ncol(df)]
metag_train <- metag_train[, (metag_train > 0 ) %>% colSums() > 20]
metag_val <- df[df$X0==1, colnames(metag_train)]

metag_train <- metag_train[, (metag_val > 0 ) %>% colSums() > 20]
metag_val <- metag_val[, (metag_val > 0 ) %>% colSums() > 20]

metab <- md[, 4:748] / md[, 4:748] %>% rowSums
# metab <- metab[, ( metab != 0 ) %>% colSums() > 200]

metab <- metab[, ( metab[row.names(metag_train), ] %>% 
                     apply(MARGIN=2, FUN = function(x) length(unique(x))) > 5 )]


melonnpan.train(metab = metab[row.names(metag_train),], 
                metag =   metag_train / metag_train %>% rowSums , 
                output='melonnpan_out2/'
                )

list.files('melonnpan_out/')



melonnpan.predict( metag_val / metag_val %>% rowSums, 
                   weight.matrix = 'melonnpan_out2/MelonnPan_Trained_Weights.txt',
                   train.metag = metag_train / metag_train %>% rowSums,
                   output='melonnpan_out2/')


metab %>% write_csv('melonnpan_out2/true_metabs.csv')
```


```{r}
library(tidyverse)
```


```{r}

df <- read.csv('mm_to_mp1/input.csv', row.names=1)

metag_train <- df[df$X0==1, 2:ncol(df)]
metag_train <- metag_train[, (metag_train > 0 ) %>% colSums() > 150]
metag_val <- df[df$X0!=1, colnames(metag_train)]

metag_train <- metag_train[, (metag_val > 0 ) %>% colSums() > 25]
metag_val <- metag_val[, (metag_val > 0 ) %>% colSums() > 25]

metab <- md[, 4:748] / md[, 4:748] %>% rowSums
metab <- metab[, ( metab != 0 ) %>% colSums() > 200]

metab <- metab[, ( metab %>% apply(MARGIN=2, FUN = function(x) length(unique(x))) > 5 )]


melonnpan.train(metab = metab[row.names(metag_train),], 
                metag =   metag_train / metag_train %>% rowSums , 
                output='mm_to_mp1/', 
                cutoff=1e3#.5
                )

# ?melonnpan.train

# list.files('melonnpan_out/')



melonnpan.predict( metag_val / metag_val %>% rowSums, 
                   weight.matrix = 'mm_to_mp1/MelonnPan_Trained_Weights.txt',
                   train.metag = metag_train / metag_train %>% rowSums,
                   output='mm_to_mp1/')


metab %>% write_csv('mm_to_mp1/true_metabs.csv')

```


```{r}
df <- read.csv('mm_to_mp2/input.csv', row.names=1)

metag_train <- df[df$X0!=1, 2:ncol(df)]
metag_train <- metag_train[, (metag_train > 0 ) %>% colSums() > 20]
metag_val <- df[df$X0==1, colnames(metag_train)]

metag_train <- metag_train[, (metag_val > 0 ) %>% colSums() > 20]
metag_val <- metag_val[, (metag_val > 0 ) %>% colSums() > 20]

metab <- md[, 4:748] / md[, 4:748] %>% rowSums
# metab <- metab[, ( metab != 0 ) %>% colSums() > 200]

metab <- metab[, ( metab[row.names(metag_train), ] %>% 
                     apply(MARGIN=2, FUN = function(x) length(unique(x))) > 5 )]


melonnpan.train(metab = metab[row.names(metag_train),], 
                metag =   metag_train / metag_train %>% rowSums , 
                output='mm_to_mp2/'
                )

# list.files('melonnpan_out/')



melonnpan.predict( metag_val / metag_val %>% rowSums, 
                   weight.matrix = 'mm_to_mp2/MelonnPan_Trained_Weights.txt',
                   train.metag = metag_train / metag_train %>% rowSums,
                   output='mm_to_mp2/')


metab %>% write_csv('mm_to_mp2/true_metabs.csv')
```




# power analysis for tal


```{r}
power.prop.test(389, p1=.95, power=.8, alternative='one.sided')


plot( 1:98/100, 
sapply( 1:98/100, 
  function(x){
power.prop.test(389, p1=x, power=.8, alternative='one.sided')$p2 - x
  }) ,
  xlab = 'control proportion', 
  ylab = 'detectable difference in proportion'
)

?

sapply( 1:98/100, 
  function(x){
power.prop.test(389, p1=x, power=.8, alternative='one.sided')$p2 - x
  }, ) 



```




```{r}
n_feats <- 100
n_samps <- 389*2
samples <- SparseDOSSA2(template = fitted_sparsedossa_vag_samples, 
                            n_sample=n_samps, 
                            n_feature = n_feats , 
                            median_read_depth = 10000, 
                            verbose = F)$simulated_data %>% t()

sapply()

samples %>% colMeans() %>% hist()

samples[sample.int(n_samps, size= 10, replace=F), 
        sample.int(n_feats, size= 20, replace=F) ] %>% colMeans()


x <- ( 1e-12 + samples[1:389,] %>% colMeans() ) 
plot(x, 
     x %>%
  sapply( function(x){
        power.prop.test(389, p1=x, power=.8, alternative='one.sided')$p2 - x
          } ),
  xlab = 'control proportion', 
  ylab = 'detectable difference in proportion'
)
```

```{r}
library(SparseDOSSA2)
library(pwr)
```


```{r}
powers <- c()
sample_size <- 389
mm <- c()
sds <- c()
s1 <- c()
s2 <- c()
n_samps <- 389
samps1 <-  389
samps2 <-  389
n_iters <- 100
n_feats <- 100

cases <- list(
              # c(389, 389), 
              # c(389, 467), 
              # c(75,703), 
              # c(75, 314), 
              # c(79, 79), 
              # c(42,42)
              c(389,778)
              )

for(j in 1:length(cases)){
  case <- cases[[j]]
  print(case)
  samps1 <- case[1]
  samps2 <- case[2]
  for( pow_level in c(0.8, 0.9)){
      mean_effect <- c()
      for(i in 1:n_iters){
        samples <- SparseDOSSA2(template = fitted_sparsedossa_vag_samples, 
                                      n_sample=n_samps, 
                                      n_feature = n_feats , 
                                      median_read_depth = 10000, 
                                      verbose = F)$simulated_data %>% t()
        
        test_inds <-  sample.int(n_feats, size= 10, replace=F)
        effect <- rep(0, n_feats)
        effect[test_inds] <- 1 / length(test_inds)
        
        
        
        val <- samples[, test_inds] %>% 
                            colMeans() %>% 
                            mean()
        h <- pwr.2p2n.test(n1=samps1, n2=samps2, sig.level=5e-4, power=pow_level, alternative='less')$h
        range <- seq(val, 1, 1e-6)
        tmp1 <-  ( ES.h(
                         val,
                         range
                   ) + abs(h)  ) %>% abs()
        
       mean_effect <- c(mean_effect,  range[ which(tmp1==min(tmp1)) ] - val )
        
        
       
       # power.prop.test( n = samps1, 
       #                  p1=val,
       #                  sig.level=5e-4,
       #                  power=pow_level, alternative='one.sided')$p2
       #  
        
        
      #   mean_effect <- c(mean_effect, samples[, test_inds] %>%
      #                                       colMeans() %>% 
      #                                       mean() %>%
      #                      sapply(function(x) power.prop.test( n = smp_size, #c(samps1, samps2),#sample_size,
      #                                                 p1=x,
      #                                                 sig.level=5e-4,
      #                                                 power=pow_level, alternative='one.sided')$p2 - x)
      #                     )
      }
      mm <- c(mm, mean(mean_effect))
      sds <- c(sds, sd(mean_effect))
      powers <- c( powers, pow_level)
      s1 <- c(s1, samps1)
      s2<- c(s2, samps2)
    }
  }

data.frame( mean_effect=mm, 
            stdv=sds, 
            powers=powers, 
            samp_size1=s1, 
            samp_size2=s2) 


val <- samples[, test_inds] %>% 
                colMeans() %>% 
                mean()

power.prop.test( n = samps1, #c(samps1, samps2),#sample_size,
                              p1=val,
                              sig.level=5e-4,
                              power=pow_level, alternative='one.sided')$p2

h <- pwr.2p2n.test(n1=samps1, n2=samps2, sig.level=5e-4, power=pow_level, alternative='less')$h
range <- seq(0, 1, 1e-6)
tmp1 <-  ( ES.h(
                 val, 
                 range[range>val]
           ) + abs(h)  ) %>% abs() 

tmp1[ which(tmp1==min(tmp1)) ]


?pwr.2p2n.test

ES.h(0.01120616, 
     0.07899088)



plot( ( ES.h(range[range>val], 
           val) - h  ) %>% abs() )

seq(0, 1, 1e-4)
## h = abs(2*asin(sqrt(p1))-2*asin(sqrt(p2))
2*asin(sqrt(p1)) - h 

invas


?pwr.2p2n.test


?pwr.2p2n.test


boxplot( mean_effect,
          ylab = 'average detectable effect size'
         )
# ?boxplot
# 
# x <- ( 1e-12 + samples[, test_inds] %>% colMeans())
# plot(x,
#      x %>%
#   sapply( function(x){
#         power.prop.test(389,
#                         p1=x,
#                         sig.level=0.005,
#                         power=.8, alternative='one.sided')$p2 - x
#           } ),
#   xlab = 'control proportion',
#   ylab = 'detectable difference in proportion'
# )

plot(ES.h( val, range ))

plot( ( ES.h(
                         val,
                         range
                   ) %>% abs()-abs(h) )
      
      
      tmp1 <- ES.h( val,
                         range
                   ) %>% abs()-abs(h)
```


```{r}
library(curatedMetagenomicData)

curatedMetagenomicData::sampleMetadata
```



```{r}
evaluate_mising_prop <- function(m, samples__){
  
    baseline_samples <-  samples__[1:(n_samps/2),] %>% apply(MARGIN=1, function(x) rmultinom(1, 10000, x)) %>% t()
    test_inds <-  sample.int(n_feats, size= 10, replace=F)
    
    effect <- rep(0, n_feats)
    effect[test_inds] <- 1 / length(test_inds)
    
    control_samples <- samples__[(n_samps/2):n_samps,] %>% apply(MARGIN=1, function(x) rmultinom(1, 10000, (1-m)*x + m*effect)) %>% t()
    control_samples <- control_samples/rowSums(control_samples)
    baseline_samples <- baseline_samples/rowSums(baseline_samples)
    
    qq <- test_inds %>% sapply( function(x, 
                               bs=baseline_samples,
                               cs=control_samples)t.test(bs[, x],
                                                         cs[, x],
                                                         alternative = 'less'
                                                         )$p.value) 
    
    return(p.adjust(qq, method = 'bonferroni'))
    }

result_pvals <- c()
mixing_plot_vals <- c()

n_iters <- 100
for(i in 1:n_iters){
  print(i)
  samples <- SparseDOSSA2(template = fitted_sparsedossa_vag_samples, 
                              n_sample=n_samps, 
                              n_feature = n_feats , 
                              median_read_depth = 10000, 
                              verbose = F)$simulated_data %>% t()
  
  mixing_vals <-  c(1e-4, 0.001, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07,0.08, 0.09, 0.1, 0.2, 0.3, 0.4, 0.5)
  results <- mixing_vals %>% 
    sapply( function(m) evaluate_mising_prop(m, samples__=samples))
  
  result_pvals <- c(result_pvals, results %>% apply(MARGIN=2, mean) )
  mixing_plot_vals <- c(mixing_plot_vals, mixing_vals)
  
}

plot(mixing_plot_vals, 
     result_pvals, 
     xlab = 'm', 
     ylab = 'mean_corrected_pvals')


data.frame(pvals:result_pvals, )

```








